[package]
name = "gb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
get_set = { path = "../lib/get_set" }
lmg_offset = { path = "../lib/lmg_offset" }
lazy_static = "1.4.0"
libc = "0.2.139"
